name       : python-threadpoolctl
version    : 3.1.0
release    : 2
source     :
    - https://github.com/joblib/threadpoolctl/archive/refs/tags/3.1.0.tar.gz : 449b806f9147a3cf28ed7ec6389dbff9c450331d695873ab75dea79fe661f1e7
license    : BSD-3-Clause
component  : programming.python
summary    : Python helpers to limit the number of threads used in native libraries that handle their own internal threadpool (BLAS and OpenMP implementations)
description: |
    Python helpers to limit the number of threads used in the threadpool-backed of common native libraries used for scientific computing and data science (e.g. BLAS and OpenMP). Fine control of the underlying thread-pool size can be useful in workloads that involve nested parallelism so as to mitigate oversubscription issues.
builddeps  :
    - python-build
    - python-flit
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
